### ISSUE TITLE
Silly Cats will spontaniously duplicate

### ISSUE THREAD

**Issue by beanjo55** [User9684/silly-cat#3]
**Expected Behavior:**
Silly Cats will remain at their current numbers

**Actual Behavior:**
At random, Silly Cats will duplicate in a guild

**Steps to Reproduce:**
- Create a Discord guild
- Introduce a Silly Cat
- Observe behavior and monitor for duplicates

The duplication also appears to speed up with more silly behavior in a guild.

**Comment by User9684** [comment]
Sorry, the silly cat dupe will not be fixed
